// <auto-generated />
using System;
using FantasyGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FantasyGame.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230309182329_relacionamentotabela")]
    partial class relacionamentotabela
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FantasyGame.Entities.Classificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Campeao")
                        .HasMaxLength(350)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("PartidasId")
                        .HasColumnType("int");

                    b.Property<string>("Terceiro")
                        .HasMaxLength(350)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Vice")
                        .HasMaxLength(350)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("PartidasId");

                    b.ToTable("Classificacao", (string)null);
                });

            modelBuilder.Entity("FantasyGame.Entities.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTimeFutebol")
                        .HasColumnType("int");

                    b.Property<string>("Resultados")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("TimeFutebolId")
                        .HasColumnType("int");

                    b.Property<string>("Times")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("TimeFutebolId");

                    b.ToTable("Partida", (string)null);
                });

            modelBuilder.Entity("FantasyGame.Entities.TimeFutebol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeTime")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Time", (string)null);
                });

            modelBuilder.Entity("FantasyGame.Entities.Classificacao", b =>
                {
                    b.HasOne("FantasyGame.Entities.Partida", "Partidas")
                        .WithMany("Classificacao")
                        .HasForeignKey("PartidasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Classificacao_Partidas");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("FantasyGame.Entities.Partida", b =>
                {
                    b.HasOne("FantasyGame.Entities.TimeFutebol", "TimeFutebol")
                        .WithMany("Partida")
                        .HasForeignKey("TimeFutebolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_TimeFutebol_Partida");

                    b.Navigation("TimeFutebol");
                });

            modelBuilder.Entity("FantasyGame.Entities.Partida", b =>
                {
                    b.Navigation("Classificacao");
                });

            modelBuilder.Entity("FantasyGame.Entities.TimeFutebol", b =>
                {
                    b.Navigation("Partida");
                });
#pragma warning restore 612, 618
        }
    }
}
